### ISSUE TITLE
This sample doesn't work 

### ISSUE THREAD

**Issue by JemmyWong** [estruyf/cypress-msteams-sample#1]
Hi, I followed the `How to start` orders, but it failed to run the test.

My versions:
Cypress Version 4.11.0 (4.11.0.401788)
Chrome Version 86.0.4240.111 (Official Build) (x86_64)

Microsoft Teams
1. Check if we can login into Microsoft Teamsfailed
    CypressError
    cy.task('TeamsAuth') failed with the following error:
    ```
    > Timeout 30000ms exceeded during page.waitForSelector.
    ================ page.waitForSelector logs ================
    [api] waiting for selector "[data-tid=newMessageFooter]" to be visible
    [api]   selector resolved to hidden <div data-tid="newMessageFooter" class="ts-new-messag…>…</div>
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

    Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: Microsoft Teams
    cypress/support/commands.ts:42:6
    40 | 
    41 |   // Call the Microsoft Teams Authentication method in order to retrieve all the cookies and local storage
    42 |   cy.task('TeamsAuth', config).then((data: { cookies: Cookie[], localStorage: KeyValuePair[] }) => {
       |      ^
    43 | 
    44 |     // Returns the correct SameSite for Cypress
    45 |     const getCookieSameSite = (sameSite: "Strict" | "Lax" | "None"): Cypress.SameSiteStatus => { 
    ```

    <details>
    <summary>View stack trace</summary>
    at <unknown> (https://teams.microsoft.com/__cypress/runner/cypress_runner.js:158370:20)

    From previous event:
    at Context.task (https://teams.microsoft.com/__cypress/runner/cypress_runner.js:158352:19)

    From Your Spec Code:
    at Context.eval (cypress/support/commands.ts:42:6)

    From Node.js Internals:
    TimeoutError: Timeout 30000ms exceeded during page.waitForSelector.

    \================ page.waitForSelector logs \================
    [api] waiting for selector "[data-tid=newMessageFooter]" to be visible
    [api]   selector resolved to hidden <div data-tid="newMessageFooter" class="ts-new-messag…>…</div>
    \============================================================

    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at ProgressController.run (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/progress.js:73:31)
    at Object.runAbortableTask (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/progress.js:29:24)
    at Page._runAbortableTask (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:86:28)
    at Frame.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/frames.js:384:28)
    at Frame.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/helper.js:79:32)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:131:62)
    at Page._attributeToPage (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:356:21)
    at Page.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:131:22)
    at Page.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/helper.js:79:32)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:54:15)
    at step (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:33:24)
    at Object.next (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:14:54)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:8:72)
    at new Promise (<anonymous>)
    at __awaiter (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:4:13)
    at getCookies (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:126:13)
    -- ASYNC --
    at Frame.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/helper.js:78:24)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:131:62)
    at Page._attributeToPage (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:356:21)
    at Page.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/page.js:131:22)
    at Page.waitForSelector (/Users/jemmy/Downloads/cypress-msteams-sample-master/node_modules/playwright-chromium/lib/helper.js:79:32)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:54:15)
    at step (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:33:24)
    at Object.next (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:14:54)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:8:72)
    at new Promise (<anonymous>)
    at __awaiter (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:4:13)
    at getCookies (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:126:13)
    at <unknown> (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:42:26)
    at step (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:33:24)
    at Object.next (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:14:54)
    at fulfilled (/Users/jemmy/Downloads/cypress-msteams-sample-master/cypress/plugins/teams-auth/index.ts:5:59)
    </details>
2. Check if Microsoft Teams is loaded correctlyprocessing
3. Check if we can start chattingprocessing
3. Check if we can reply to a chat

**Comment by estruyf** [comment]
This was because the new conversation button got introduced instead of the conversation input field. I changed the logic to the new button and all should work fine again.
